/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/world.glb -t -k 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ForwardedRef, forwardRef, useEffect, useRef } from "react";
import { useExplode } from "../hooks/useExplode";

type GLTFResult = GLTF & {
  nodes: {
    Origin: THREE.Mesh;
    Icosphere_cell: THREE.Mesh;
    Icosphere_cell001: THREE.Mesh;
    Icosphere_cell002: THREE.Mesh;
    Icosphere_cell003: THREE.Mesh;
    Icosphere_cell004: THREE.Mesh;
    Icosphere_cell005: THREE.Mesh;
    Icosphere_cell006: THREE.Mesh;
    Icosphere_cell007: THREE.Mesh;
    Icosphere_cell008: THREE.Mesh;
    Icosphere_cell009: THREE.Mesh;
    Icosphere_cell010: THREE.Mesh;
    Icosphere_cell011: THREE.Mesh;
    Icosphere_cell012: THREE.Mesh;
    Icosphere_cell013: THREE.Mesh;
    Icosphere_cell014: THREE.Mesh;
    Icosphere_cell015: THREE.Mesh;
    Icosphere_cell016: THREE.Mesh;
    Icosphere_cell017: THREE.Mesh;
    Icosphere_cell018: THREE.Mesh;
    Icosphere_cell019: THREE.Mesh;
    Icosphere_cell020: THREE.Mesh;
    Icosphere_cell021: THREE.Mesh;
    Icosphere_cell022: THREE.Mesh;
    Icosphere_cell023: THREE.Mesh;
    Icosphere_cell024: THREE.Mesh;
    Icosphere_cell025: THREE.Mesh;
    Icosphere_cell026: THREE.Mesh;
    Icosphere_cell027: THREE.Mesh;
    Icosphere_cell028: THREE.Mesh;
    Icosphere_cell029: THREE.Mesh;
    Icosphere_cell030: THREE.Mesh;
    Icosphere_cell031: THREE.Mesh;
    Icosphere_cell032: THREE.Mesh;
    Icosphere_cell033: THREE.Mesh;
    Icosphere_cell034: THREE.Mesh;
    Icosphere_cell035: THREE.Mesh;
    Icosphere_cell036: THREE.Mesh;
    Icosphere_cell037: THREE.Mesh;
    Icosphere_cell038: THREE.Mesh;
    Icosphere_cell039: THREE.Mesh;
    Icosphere_cell040: THREE.Mesh;
    Icosphere_cell041: THREE.Mesh;
    Icosphere_cell042: THREE.Mesh;
    Icosphere_cell043: THREE.Mesh;
    Icosphere_cell044: THREE.Mesh;
    Icosphere_cell045: THREE.Mesh;
    Icosphere_cell046: THREE.Mesh;
    Icosphere_cell047: THREE.Mesh;
    Icosphere_cell048: THREE.Mesh;
    Icosphere_cell049: THREE.Mesh;
    Icosphere_cell050: THREE.Mesh;
    Icosphere_cell051: THREE.Mesh;
    Icosphere_cell052: THREE.Mesh;
    Icosphere_cell053: THREE.Mesh;
    Icosphere_cell054: THREE.Mesh;
    Icosphere_cell055: THREE.Mesh;
    Icosphere_cell056: THREE.Mesh;
    Icosphere_cell057: THREE.Mesh;
    Icosphere_cell058: THREE.Mesh;
    Icosphere_cell059: THREE.Mesh;
    Icosphere_cell060: THREE.Mesh;
    Icosphere_cell061: THREE.Mesh;
    Icosphere_cell062: THREE.Mesh;
    Icosphere_cell063: THREE.Mesh;
    Icosphere_cell064: THREE.Mesh;
    Icosphere_cell065: THREE.Mesh;
    Icosphere_cell066: THREE.Mesh;
    Icosphere_cell067: THREE.Mesh;
    Icosphere_cell068: THREE.Mesh;
    Icosphere_cell069: THREE.Mesh;
    Icosphere_cell070: THREE.Mesh;
    Icosphere_cell071: THREE.Mesh;
    Icosphere_cell072: THREE.Mesh;
    Icosphere_cell073: THREE.Mesh;
    Icosphere_cell074: THREE.Mesh;
    Icosphere_cell075: THREE.Mesh;
    Icosphere_cell076: THREE.Mesh;
    Icosphere_cell077: THREE.Mesh;
    Icosphere_cell078: THREE.Mesh;
    Icosphere_cell079: THREE.Mesh;
    Icosphere_cell080: THREE.Mesh;
    Icosphere_cell081: THREE.Mesh;
    Icosphere_cell082: THREE.Mesh;
    Icosphere_cell083: THREE.Mesh;
    Icosphere_cell084: THREE.Mesh;
    Icosphere_cell085: THREE.Mesh;
    Icosphere_cell086: THREE.Mesh;
    Icosphere_cell087: THREE.Mesh;
    Icosphere_cell088: THREE.Mesh;
    Icosphere_cell089: THREE.Mesh;
    Icosphere_cell090: THREE.Mesh;
    Icosphere_cell091: THREE.Mesh;
    Icosphere_cell092: THREE.Mesh;
    Icosphere_cell093: THREE.Mesh;
    Icosphere_cell094: THREE.Mesh;
    Icosphere_cell095: THREE.Mesh;
    Icosphere_cell096: THREE.Mesh;
    Icosphere_cell097: THREE.Mesh;
    Icosphere_cell098: THREE.Mesh;
    Icosphere_cell099: THREE.Mesh;
  };
  materials: {
    rock: THREE.MeshStandardMaterial;
  };
};

interface groupProps {
  position: [number, number, number];
  scale: [number, number, number];
  collision: boolean;
}

export const World = forwardRef(
  (props: groupProps, ref: ForwardedRef<THREE.Group>) => {
    const { nodes, materials } = useGLTF("./world.glb") as GLTFResult;

    const groupRef = useRef<THREE.Group>(null);
    const easeOutCubic = (t: number) => --t * t * t + 1;

    //FORWARDING REF
    useEffect(() => {
      if (ref) {
        if (typeof ref === "function") {
          ref(groupRef.current); // Handle callback refs
        } else {
          ref.current = groupRef.current; // Handle object refs
        }
      }
    }, [ref]);

    useExplode(groupRef, props.collision, easeOutCubic);

    return (
      <group
        position={props.position}
        dispose={null}
        ref={groupRef}
        scale={props.scale}
      >
        <mesh
          name="Origin"
          geometry={nodes.Origin.geometry}
          material={materials.rock}
        />
        <mesh
          name="Icosphere_cell"
          geometry={nodes.Icosphere_cell.geometry}
          material={materials.rock}
          position={[-1.646, -0.343, -0.706]}
        />
        <mesh
          name="Icosphere_cell001"
          geometry={nodes.Icosphere_cell001.geometry}
          material={materials.rock}
          position={[-1.629, 0.146, 0.766]}
        />
        <mesh
          name="Icosphere_cell002"
          geometry={nodes.Icosphere_cell002.geometry}
          material={materials.rock}
          position={[-1.318, -0.001, -1.25]}
        />
        <mesh
          name="Icosphere_cell003"
          geometry={nodes.Icosphere_cell003.geometry}
          material={materials.rock}
          position={[1.107, -0.016, 1.472]}
        />
        <mesh
          name="Icosphere_cell004"
          geometry={nodes.Icosphere_cell004.geometry}
          material={materials.rock}
          position={[0.547, -0.558, -1.627]}
        />
        <mesh
          name="Icosphere_cell005"
          geometry={nodes.Icosphere_cell005.geometry}
          material={materials.rock}
          position={[1.026, 0.134, -1.52]}
        />
        <mesh
          name="Icosphere_cell006"
          geometry={nodes.Icosphere_cell006.geometry}
          material={materials.rock}
          position={[0.775, 1.561, -0.689]}
        />
        <mesh
          name="Icosphere_cell007"
          geometry={nodes.Icosphere_cell007.geometry}
          material={materials.rock}
          position={[1.332, 1.25, 0.454]}
        />
        <mesh
          name="Icosphere_cell008"
          geometry={nodes.Icosphere_cell008.geometry}
          material={materials.rock}
          position={[0.329, 0.454, 1.706]}
        />
        <mesh
          name="Icosphere_cell009"
          geometry={nodes.Icosphere_cell009.geometry}
          material={materials.rock}
          position={[1.513, -0.295, -0.907]}
        />
        <mesh
          name="Icosphere_cell010"
          geometry={nodes.Icosphere_cell010.geometry}
          material={materials.rock}
          position={[0.523, -1.222, -1.118]}
        />
        <mesh
          name="Icosphere_cell011"
          geometry={nodes.Icosphere_cell011.geometry}
          material={materials.rock}
          position={[1.687, 0.088, 0.607]}
        />
        <mesh
          name="Icosphere_cell012"
          geometry={nodes.Icosphere_cell012.geometry}
          material={materials.rock}
          position={[-1.564, -0.931, -0.235]}
        />
        <mesh
          name="Icosphere_cell013"
          geometry={nodes.Icosphere_cell013.geometry}
          material={materials.rock}
          position={[1.205, -1.441, -0.104]}
        />
        <mesh
          name="Icosphere_cell014"
          geometry={nodes.Icosphere_cell014.geometry}
          material={materials.rock}
          position={[-0.035, -1.12, -1.537]}
        />
        <mesh
          name="Icosphere_cell015"
          geometry={nodes.Icosphere_cell015.geometry}
          material={materials.rock}
          position={[-1.309, -0.919, -0.891]}
        />
        <mesh
          name="Icosphere_cell016"
          geometry={nodes.Icosphere_cell016.geometry}
          material={materials.rock}
          position={[-1.594, 0.982, -0.268]}
        />
        <mesh
          name="Icosphere_cell017"
          geometry={nodes.Icosphere_cell017.geometry}
          material={materials.rock}
          position={[-0.44, 1.331, 1.058]}
        />
        <mesh
          name="Icosphere_cell018"
          geometry={nodes.Icosphere_cell018.geometry}
          material={materials.rock}
          position={[0.497, -1.718, -0.307]}
        />
        <mesh
          name="Icosphere_cell019"
          geometry={nodes.Icosphere_cell019.geometry}
          material={materials.rock}
          position={[1.662, 0.76, -0.317]}
        />
        <mesh
          name="Icosphere_cell020"
          geometry={nodes.Icosphere_cell020.geometry}
          material={materials.rock}
          position={[0.858, 1.529, -0.11]}
        />
        <mesh
          name="Icosphere_cell021"
          geometry={nodes.Icosphere_cell021.geometry}
          material={materials.rock}
          position={[-1.869, -0.213, -0.181]}
        />
        <mesh
          name="Icosphere_cell022"
          geometry={nodes.Icosphere_cell022.geometry}
          material={materials.rock}
          position={[1.597, 0.552, 0.491]}
        />
        <mesh
          name="Icosphere_cell023"
          geometry={nodes.Icosphere_cell023.geometry}
          material={materials.rock}
          position={[-1.729, 0.555, 0.276]}
        />
        <mesh
          name="Icosphere_cell024"
          geometry={nodes.Icosphere_cell024.geometry}
          material={materials.rock}
          position={[-0.236, 0.882, -1.582]}
        />
        <mesh
          name="Icosphere_cell025"
          geometry={nodes.Icosphere_cell025.geometry}
          material={materials.rock}
          position={[-1.529, -0.747, 0.684]}
        />
        <mesh
          name="Icosphere_cell026"
          geometry={nodes.Icosphere_cell026.geometry}
          material={materials.rock}
          position={[0.736, 1.204, 1.046]}
        />
        <mesh
          name="Icosphere_cell027"
          geometry={nodes.Icosphere_cell027.geometry}
          material={materials.rock}
          position={[-1.315, 1.206, 0.655]}
        />
        <mesh
          name="Icosphere_cell028"
          geometry={nodes.Icosphere_cell028.geometry}
          material={materials.rock}
          position={[1.726, -0.485, 0.609]}
        />
        <mesh
          name="Icosphere_cell029"
          geometry={nodes.Icosphere_cell029.geometry}
          material={materials.rock}
          position={[-0.764, 1.522, -0.815]}
        />
        <mesh
          name="Icosphere_cell030"
          geometry={nodes.Icosphere_cell030.geometry}
          material={materials.rock}
          position={[1.028, 1.076, 0.982]}
        />
        <mesh
          name="Icosphere_cell031"
          geometry={nodes.Icosphere_cell031.geometry}
          material={materials.rock}
          position={[1.252, -0.776, 1.17]}
        />
        <mesh
          name="Icosphere_cell032"
          geometry={nodes.Icosphere_cell032.geometry}
          material={materials.rock}
          position={[-0.014, -1.563, -0.915]}
        />
        <mesh
          name="Icosphere_cell033"
          geometry={nodes.Icosphere_cell033.geometry}
          material={materials.rock}
          position={[1.829, -0.153, 0.001]}
        />
        <mesh
          name="Icosphere_cell034"
          geometry={nodes.Icosphere_cell034.geometry}
          material={materials.rock}
          position={[1.308, -0.851, -0.972]}
        />
        <mesh
          name="Icosphere_cell035"
          geometry={nodes.Icosphere_cell035.geometry}
          material={materials.rock}
          position={[-1.214, -1.201, -0.518]}
        />
        <mesh
          name="Icosphere_cell036"
          geometry={nodes.Icosphere_cell036.geometry}
          material={materials.rock}
          position={[-1.015, -1.182, 0.906]}
        />
        <mesh
          name="Icosphere_cell037"
          geometry={nodes.Icosphere_cell037.geometry}
          material={materials.rock}
          position={[-1.252, 0.505, -1.118]}
        />
        <mesh
          name="Icosphere_cell038"
          geometry={nodes.Icosphere_cell038.geometry}
          material={materials.rock}
          position={[1.46, 0.568, 1.057]}
        />
        <mesh
          name="Icosphere_cell039"
          geometry={nodes.Icosphere_cell039.geometry}
          material={materials.rock}
          position={[-0.347, 1.256, -1.197]}
        />
        <mesh
          name="Icosphere_cell040"
          geometry={nodes.Icosphere_cell040.geometry}
          material={materials.rock}
          position={[0.262, -1.183, -1.421]}
        />
        <mesh
          name="Icosphere_cell041"
          geometry={nodes.Icosphere_cell041.geometry}
          material={materials.rock}
          position={[1.632, 0.158, -0.736]}
        />
        <mesh
          name="Icosphere_cell042"
          geometry={nodes.Icosphere_cell042.geometry}
          material={materials.rock}
          position={[-0.507, 0.451, -1.687]}
        />
        <mesh
          name="Icosphere_cell043"
          geometry={nodes.Icosphere_cell043.geometry}
          material={materials.rock}
          position={[1.048, 1.457, 0.137]}
        />
        <mesh
          name="Icosphere_cell044"
          geometry={nodes.Icosphere_cell044.geometry}
          material={materials.rock}
          position={[0.38, 1.386, -1.226]}
        />
        <mesh
          name="Icosphere_cell045"
          geometry={nodes.Icosphere_cell045.geometry}
          material={materials.rock}
          position={[0.513, -1.665, 0.582]}
        />
        <mesh
          name="Icosphere_cell046"
          geometry={nodes.Icosphere_cell046.geometry}
          material={materials.rock}
          position={[-1.427, 0.541, 1.058]}
        />
        <mesh
          name="Icosphere_cell047"
          geometry={nodes.Icosphere_cell047.geometry}
          material={materials.rock}
          position={[-0.24, -1.822, 0.149]}
        />
        <mesh
          name="Icosphere_cell048"
          geometry={nodes.Icosphere_cell048.geometry}
          material={materials.rock}
          position={[0.795, -1.44, -0.918]}
        />
        <mesh
          name="Icosphere_cell049"
          geometry={nodes.Icosphere_cell049.geometry}
          material={materials.rock}
          position={[0.712, 1.541, 0.502]}
        />
        <mesh
          name="Icosphere_cell050"
          geometry={nodes.Icosphere_cell050.geometry}
          material={materials.rock}
          position={[1.272, -0.619, -1.146]}
        />
        <mesh
          name="Icosphere_cell051"
          geometry={nodes.Icosphere_cell051.geometry}
          material={materials.rock}
          position={[-0.243, -0.503, -1.657]}
        />
        <mesh
          name="Icosphere_cell052"
          geometry={nodes.Icosphere_cell052.geometry}
          material={materials.rock}
          position={[-0.731, 1.518, -0.064]}
        />
        <mesh
          name="Icosphere_cell053"
          geometry={nodes.Icosphere_cell053.geometry}
          material={materials.rock}
          position={[-1.514, 1.098, 0.169]}
        />
        <mesh
          name="Icosphere_cell054"
          geometry={nodes.Icosphere_cell054.geometry}
          material={materials.rock}
          position={[-0.222, -1.495, 1.126]}
        />
        <mesh
          name="Icosphere_cell055"
          geometry={nodes.Icosphere_cell055.geometry}
          material={materials.rock}
          position={[-1.386, -0.459, -1.186]}
        />
        <mesh
          name="Icosphere_cell056"
          geometry={nodes.Icosphere_cell056.geometry}
          material={materials.rock}
          position={[-0.58, 1.725, 0.232]}
        />
        <mesh
          name="Icosphere_cell057"
          geometry={nodes.Icosphere_cell057.geometry}
          material={materials.rock}
          position={[1.39, -1.033, 0.247]}
        />
        <mesh
          name="Icosphere_cell058"
          geometry={nodes.Icosphere_cell058.geometry}
          material={materials.rock}
          position={[-1.188, -0.087, 1.407]}
        />
        <mesh
          name="Icosphere_cell059"
          geometry={nodes.Icosphere_cell059.geometry}
          material={materials.rock}
          position={[0.875, 0.778, 1.498]}
        />
        <mesh
          name="Icosphere_cell060"
          geometry={nodes.Icosphere_cell060.geometry}
          material={materials.rock}
          position={[1.47, -0.882, -0.657]}
        />
        <mesh
          name="Icosphere_cell061"
          geometry={nodes.Icosphere_cell061.geometry}
          material={materials.rock}
          position={[-0.836, -1.615, -0.222]}
        />
        <mesh
          name="Icosphere_cell062"
          geometry={nodes.Icosphere_cell062.geometry}
          material={materials.rock}
          position={[0.272, 0.069, 1.734]}
        />
        <mesh
          name="Icosphere_cell063"
          geometry={nodes.Icosphere_cell063.geometry}
          material={materials.rock}
          position={[-1.3, 1.02, -0.81]}
        />
        <mesh
          name="Icosphere_cell064"
          geometry={nodes.Icosphere_cell064.geometry}
          material={materials.rock}
          position={[0.867, -1.024, -1.099]}
        />
        <mesh
          name="Icosphere_cell065"
          geometry={nodes.Icosphere_cell065.geometry}
          material={materials.rock}
          position={[0.069, 1.836, -0.224]}
        />
        <mesh
          name="Icosphere_cell066"
          geometry={nodes.Icosphere_cell066.geometry}
          material={materials.rock}
          position={[1.027, -0.468, -1.411]}
        />
        <mesh
          name="Icosphere_cell067"
          geometry={nodes.Icosphere_cell067.geometry}
          material={materials.rock}
          position={[0.156, -0.263, -1.861]}
        />
        <mesh
          name="Icosphere_cell068"
          geometry={nodes.Icosphere_cell068.geometry}
          material={materials.rock}
          position={[-0.706, -0.006, 1.755]}
        />
        <mesh
          name="Icosphere_cell069"
          geometry={nodes.Icosphere_cell069.geometry}
          material={materials.rock}
          position={[-0.24, -1.129, 1.434]}
        />
        <mesh
          name="Icosphere_cell070"
          geometry={nodes.Icosphere_cell070.geometry}
          material={materials.rock}
          position={[0.956, 0.901, -1.36]}
        />
        <mesh
          name="Icosphere_cell071"
          geometry={nodes.Icosphere_cell071.geometry}
          material={materials.rock}
          position={[0.687, -1.169, 1.228]}
        />
        <mesh
          name="Icosphere_cell072"
          geometry={nodes.Icosphere_cell072.geometry}
          material={materials.rock}
          position={[-1.167, 1.288, -0.517]}
        />
        <mesh
          name="Icosphere_cell073"
          geometry={nodes.Icosphere_cell073.geometry}
          material={materials.rock}
          position={[-0.759, -0.847, -1.42]}
        />
        <mesh
          name="Icosphere_cell074"
          geometry={nodes.Icosphere_cell074.geometry}
          material={materials.rock}
          position={[1.379, 1.04, 0.714]}
        />
        <mesh
          name="Icosphere_cell075"
          geometry={nodes.Icosphere_cell075.geometry}
          material={materials.rock}
          position={[0.186, 1.208, 1.386]}
        />
        <mesh
          name="Icosphere_cell076"
          geometry={nodes.Icosphere_cell076.geometry}
          material={materials.rock}
          position={[-0.158, 0.712, 1.691]}
        />
        <mesh
          name="Icosphere_cell077"
          geometry={nodes.Icosphere_cell077.geometry}
          material={materials.rock}
          position={[1.309, 1.164, -0.543]}
        />
        <mesh
          name="Icosphere_cell078"
          geometry={nodes.Icosphere_cell078.geometry}
          material={materials.rock}
          position={[-1.56, -0.983, 0.128]}
        />
        <mesh
          name="Icosphere_cell079"
          geometry={nodes.Icosphere_cell079.geometry}
          material={materials.rock}
          position={[-0.862, 0.963, 1.378]}
        />
        <mesh
          name="Icosphere_cell080"
          geometry={nodes.Icosphere_cell080.geometry}
          material={materials.rock}
          position={[1.681, -0.678, -0.23]}
        />
        <mesh
          name="Icosphere_cell081"
          geometry={nodes.Icosphere_cell081.geometry}
          material={materials.rock}
          position={[-1.06, 0.037, -1.566]}
        />
        <mesh
          name="Icosphere_cell082"
          geometry={nodes.Icosphere_cell082.geometry}
          material={materials.rock}
          position={[0.375, -0.861, -1.516]}
        />
        <mesh
          name="Icosphere_cell083"
          geometry={nodes.Icosphere_cell083.geometry}
          material={materials.rock}
          position={[1.464, 1.198, 0.077]}
        />
        <mesh
          name="Icosphere_cell084"
          geometry={nodes.Icosphere_cell084.geometry}
          material={materials.rock}
          position={[1.082, -1.18, -0.746]}
        />
        <mesh
          name="Icosphere_cell085"
          geometry={nodes.Icosphere_cell085.geometry}
          material={materials.rock}
          position={[0.308, 1.727, 0.578]}
        />
        <mesh
          name="Icosphere_cell086"
          geometry={nodes.Icosphere_cell086.geometry}
          material={materials.rock}
          position={[-0.103, -0.242, 1.862]}
        />
        <mesh
          name="Icosphere_cell087"
          geometry={nodes.Icosphere_cell087.geometry}
          material={materials.rock}
          position={[-0.596, -0.791, 1.614]}
        />
        <mesh
          name="Icosphere_cell088"
          geometry={nodes.Icosphere_cell088.geometry}
          material={materials.rock}
          position={[0.826, -0.873, -1.323]}
        />
        <mesh
          name="Icosphere_cell089"
          geometry={nodes.Icosphere_cell089.geometry}
          material={materials.rock}
          position={[-0.182, 1.781, 0.628]}
        />
        <mesh
          name="Icosphere_cell090"
          geometry={nodes.Icosphere_cell090.geometry}
          material={materials.rock}
          position={[1.649, 0.859, 0.31]}
        />
        <mesh
          name="Icosphere_cell091"
          geometry={nodes.Icosphere_cell091.geometry}
          material={materials.rock}
          position={[0.356, -0.613, 1.664]}
        />
        <mesh
          name="Icosphere_cell092"
          geometry={nodes.Icosphere_cell092.geometry}
          material={materials.rock}
          position={[-0.656, -0.073, -1.667]}
        />
        <mesh
          name="Icosphere_cell093"
          geometry={nodes.Icosphere_cell093.geometry}
          material={materials.rock}
          position={[0.33, 0.523, -1.733]}
        />
        <mesh
          name="Icosphere_cell094"
          geometry={nodes.Icosphere_cell094.geometry}
          material={materials.rock}
          position={[-1.793, -0.27, 0.503]}
        />
        <mesh
          name="Icosphere_cell095"
          geometry={nodes.Icosphere_cell095.geometry}
          material={materials.rock}
          position={[0.379, 1.346, 1.087]}
        />
        <mesh
          name="Icosphere_cell096"
          geometry={nodes.Icosphere_cell096.geometry}
          material={materials.rock}
          position={[-0.558, -1.443, -1.084]}
        />
        <mesh
          name="Icosphere_cell097"
          geometry={nodes.Icosphere_cell097.geometry}
          material={materials.rock}
          position={[-0.113, 0.071, -1.765]}
        />
        <mesh
          name="Icosphere_cell098"
          geometry={nodes.Icosphere_cell098.geometry}
          material={materials.rock}
          position={[-1.689, 0.439, -0.561]}
        />
        <mesh
          name="Icosphere_cell099"
          geometry={nodes.Icosphere_cell099.geometry}
          material={materials.rock}
          position={[-1.264, 1.359, -0.041]}
        />
      </group>
    );
  }
);

useGLTF.preload("./world.glb");
